language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
env:
  global:
    - secure: >-
        ixs4mxf5tqF+qP+lrrCnu4ljhmljXKYCsJ0gZHbytdLHmtqiz//k5Tozf5iRWD9HuQ0qGoTuGwQu1MiYoMBq9OSt+LS6AR3C44/uo/+hk/yq+mjK/Ri6AYKYuA08uHR55FTUmbUijAS09vgPgGL9FsqKjANxNc1jalZ90cp15OU=
    - secure: >-
        Pagn02PjGt5it84GEHLBGmaAqF7u2WsbEPrc1t3A7eYwZh82oGszrKDDqmVBxDlL7EICq5gdGDEMYC2iycvCyoQNW7LCQV12P0iqPITlGYhFCQbuocChEkzVC+m1RN3cf7z9wO3rZKf3nd/tfuWgFZh5VCfvpX0wPwrJPZcI1Lo=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
cache:
  directories:
    - node_modules
